config/routes.rb
SpringConference2012::Application.routes.draw do
  

  get "pages/home"
  get "pages/program"
  get "pages/schedule"
  get "pages/sponsors"
  get "pages/contact_us"
  get "pages/speakers"
  get "pages/registration"
  get "pages/educationals"
  get "pages/speaker_bios"
  get "pages/faq"
  get "pages/prizes"
  get "pages/terms_conditions"
  get "pages/venue"
  get "pages/about_calgary"
  get "pages/our_sponsors"
  get "pages/volunteers"
  get "pages/application"
  get "pages/about"
  get "pages/planning_team"
  get "pages/disclaimer"
  get "pages/testhome"
  

  root :to => "pages#home"
  match '/', :to => 'pages#home'
  match '/contact_us', :to => 'pages#contact_us'
  match '/schedule', :to => 'pages#schedule'
  match '/program', :to => 'pages#program'
  match '/sponsors', :to => 'pages#sponsors'
  match '/speakers', :to => 'pages#speakers'
  match '/registration', :to => 'pages#registration'
  match '/educationals', :to => 'pages#educationals'
  match '/speaker_bios', :to => 'pages#speaker_bios'
  match '/faq', :to => 'pages#faq'
  match '/prizes', :to => 'pages#prizes'
  match '/terms_conditions', :to => 'pages#terms_conditions'
  match '/venue', :to => 'pages#venue'
  match '/about_calgary', :to => 'pages#about_calgary'
  match '/our_sponsors', :to => 'pages#our_sponsors'
  match '/volunteers', :to => 'pages#volunteers'
  match '/application', :to => 'pages#application'
  match '/about', :to => 'pages#about'
  match '/planning_team', :to => 'pages#planning_team'
  match '/disclaimer', :to => 'pages#disclaimer'
  match '/testhome', :to => 'pages#testhome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title = "Home"
  end

  def program
	@title = "Program"
  end

  def schedule
	@title = "Schedule"
  end

  def sponsors
	@title = "Sponsors"
  end

  def contact_us
	@title = "Contact Us"
  end

  def speakers
	@title = "Speakers"
  end

  def registration
	@title = "Registration"
  end

  def educationals
	@title = "Educationals"
  end

  def speaker_bios
	@title = "Speaker Bios"
  end

  def faq
	@title = "FAQ"
  end

  def prizes
	@title = "Prizes"
  end

  def terms_conditions
	@title = "Terms & Conditions"
  end

  def venue
	@title = "Venue"
  end

  def about_calgary
	@title = "About Calgary"
  end

  def our_sponsors
	@title = "Our Sponsors"
  end

  def volunteers
	@title = "Volunteers"
  end

  def application
	@title = "Application"
  end

  def about
	@title = "About"
  end

  def planning_team
	@title = "Planning Team"
  end

  def disclaimer
	@title = "Disclaimer"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D42 Spring Convention || Take The Lead | <%= @title %></title>
	<%= csrf_meta_tag %>
	<!--[if gte IE 9]>
	  <style type="text/css">
    		.gradient {
       			filter: none;
    		}
  	  </style>
	<![endif]-->
	<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
	<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>

<script type="text/javascript">

function theRotator() {
	//Set the opacity of all images to 0
	$('div.rotator ul li').css({opacity: 0.0});
	
	//Get the first image and display it (gets set to full opacity)
	$('div.rotator ul li:first').css({opacity: 1.0});
		
	//Call the rotator function to run the slideshow, 6000 = change to next image after 6 seconds
	
	setInterval('rotate()',6000);
	
}

function rotate() {	
	//Get the first image
	var current = ($('div.rotator ul li.show')?  $('div.rotator ul li.show') : $('div.rotator ul li:first'));

    if ( current.length == 0 ) current = $('div.rotator ul li:first');

	//Get next image, when it reaches the end, rotate it back to the first image
	var next = ((current.next().length) ? ((current.next().hasClass('show')) ? $('div.rotator ul li:first') :current.next()) : $('div.rotator ul li:first'));
	
	//Un-comment the 3 lines below to get the images in random order
	
	//var sibs = current.siblings();
    //var rndNum = Math.floor(Math.random() * sibs.length );
    //var next = $( sibs[ rndNum ] );
			

	//Set the fade in effect for the next image, the show class has higher z-index
	next.css({opacity: 0.0})
	.addClass('show')
	.animate({opacity: 1.0}, 1000);

	//Hide the current image
	current.animate({opacity: 0.0}, 1000)
	.removeClass('show');
	
};



$(document).ready(function() {		
	//Load the slideshow
	theRotator();
	$('div.rotator').fadeIn(1000);
    $('div.rotator ul li').fadeIn(1000); // tweek for IE
});
</script>
</head>
<body class="twoColFixRtHdr">

<div id="container">
  <div id="header">

   <%= link_to image_tag("Banner_Medium_w980.png", :alt => "D42 Spring Convention || Take The Lead"), root_path %>
   
    
<!-- Drop-down menu -->
    
	<div id="nav">
		<ul>
			<li class="first"><%= link_to "Program", program_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "Schedule", schedule_path , :class => "nav_links" %></li>
					<li><%= link_to "Speakers", speakers_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "Registration", registration_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "FAQ", faq_path, :class => "nav_links" %></li>
					<li><%= link_to "Terms & Conditions", terms_conditions_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "Venue", venue_path, :class => "nav_links" %>
				<ul>					
					<li><%= link_to "About Calgary", about_calgary_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "Sponsors", sponsors_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "Our Sponsors", our_sponsors_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "Volunteers", volunteers_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "Application", application_path, :class => "nav_links" %></li>
				</ul>
			</li>
			<li><%= link_to "About", about_path, :class => "nav_links" %>
				<ul>
					<li><%= link_to "Planning Team", planning_team_path, :class => "nav_links" %></li>
					<li><%= link_to "Contact Us", contact_us_path, :class => "nav_links" %></li>
				</ul>
			</li>
		</ul>
	</div>
  <!-- end #header --></div>
  <div id="sidebar1">
    <%= link_to "Register", registration_path, :class => "registration_button round" %>
    <br>
   <script src="http://widgets.twimg.com/j/2/widget.js"></script>
    <script>
       new TWTR.Widget({
         version: 2,
         type: 'profile',
         rpp: 4,
         interval: 30000,
         width: 200,
         height: 250,
         theme: {
           shell: {
             background: '#004265',
             color: '#ffffff'
           },
           tweets: {
             background: '#f2df74',
             color: '#000000',
             links: '#fc3200'
           }
         },
         features: {
            scrollbar: true,
            loop: false,
            live: true,
            behavior: 'all'
         }
      }).render().setUser('D42TakeTheLead').start();
      </script>



  <!-- end #sidebar1 --></div>

<%= yield %>

<!-- This clearing element should immediately follow the #mainContent div in order to force the #container div to contain all child floats --><br class="clearfloat" />
  <div id="footer">
	<div id="top_footer"><br><br></div>
	<div id="mid_footer" class="round"><%= image_tag("Rad_calgary_Logo.png") %></div>
   
	<div id="bottom_footer">
		<%= link_to "Home", root_path, :class => "footer_left" %><p class="footer_left"> | </p>
		<%= link_to "Disclaimer", disclaimer_path, :class => "footer_left" %><p class="footer_left"> | </p>
		<%= link_to "Contact Us", contact_us_path, :class => "footer_left" %>
		<p class="footer_right">Design by Matthew Dumont</p>
	</div>    

    <br />
  <!-- end #footer --></div>
<!-- <%= debug(params) if Rails.env.development? %> -->
<!-- end #container --></div>

</body>
</html>

app/views/pages/about.html.erb
<br><h1>Toastmasters</h1>

<h2>About Toastmasters International</h2>

<p class=maintext>Since 1924, more than 4 million people around the world have become more confident
speakers and leaders because of their participation in Toastmasters. Through
practice in a safe and supporting environment, more than 270,000 members in 13,000
clubs are developing their communication and leadership skills today.</p>

<p class=maintext>The Toastmasters program offers many benefits that help people in all walks of life. As a result of participating in Toastmasters, you will:</p>

<ul class=mainlist>
<li>Increase your self-confidence</li>
<li>Become a better speaker</li>
<li>Become a better leader</li>
<li>Communicate more effectively</li>
</ul>

<p class=maintext>For more information, please visit <a href="http://www.toastmasters.org" target="_blank" class=bodytext>www.toastmasters.org</a>.</p>

<h2>About District 42</h2>
<p class=maintext>District 42 is a vibrant unit in the Toastmasters International network with more than 2,000 active members spread across 9 divisions and 56 clubs.  The District is focused on promoting communication and leadership principals within the communities and businesses of Alberta and Saskatchewan, Canada.  For more information, please visit <a href="http://www.d42.org" target="_blank" class=bodytext>www.d42.org</a>.</p> 

<h2>Find a Club near You</h2>

<p class=maintext>Want to join a Toastmasters club close to your home or office – or – coming to Calgary and looking to take in a club meeting while you’re here for the convention?  Check out the <a href="http://reports.toastmasters.org/findaclub/default.cfm?Country=Canada" target="_blank" class=bodytext>Find a Club</a> feature on the Toastmasters International site.</p> 

app/views/pages/about_calgary.html.erb
<br><h1>About Calgary</h1>

<p class="maintext">Welcome to Calgary!</p>
 
<p class="maintext">Calgary Alberta offers tourists a myriad of things to see and do.  Why not extend your stay at the Convention by a few days and see what this City really has to offer?</p> 

<p class="maintext">Rain or shine, some sample things to do in the Calgary Spring include:</p>

<ul class=mainlist>
<li>Visit the new and improved <a href="http://www.sparkscience.ca/" target="_blank" class="bodytext">Calgary Science Centre</a> opened October 29, 2011.</li>
<li>Stroll through the <a href="http://www.calgaryzoo.org/" target="_blank" class="bodytext">Calgary Zoo</a>.</li>
<li>Talk a walk or bike ride along Calgary’s beautiful <a href="http://www.calgary.ca/CSPS/Parks/Pages/Pathways/Pathways-in-Calgary.aspx" target="_blank" class="bodytext">pathways</a>.</li>
<li>See natural wonders in one of the many <a href="http://www.discovercalgary.com/Calgary/SightsAttractions/ParksGardens/" target="_blank" class="bodytext">parks</a>.</li>
<li>Ride to the top of the <a href="http://www.calgarytower.com/" target="_blank" class="bodytext">Calgary Tower</a> for a bird’s eye view of the City and surrounding area.</li>
<li>Take in a local cultural event at venues like 
<a href="http://www.stagewestcalgary.com/shows.html" target="_blank" class="bodytext">Stage West</a>, 
<a href="http://www.theatrecalgary.com/" target="_blank" class="bodytext">Theatre Calgary</a>, 
<a href="http://www.jubilations.ca/jubilations/cal_whatis.html" target="_blank" class="bodytext">Jubilations Dinner Theatre</a> or 
<a href="http://www.loosemoose.com/" target="_blank" class="bodytext">Loose Moose Theatre</a>.</li>
<li>Learn about Alberta’s history at one our many museums like the 
<a href="http://www.glenbow.org/" target="_blank" class="bodytext">Glenbow Museum</a>, 
<a href="http://www.fortcalgary.com/" target="_blank" class="bodytext">Fort Calgary</a>, 
<a href="http://www.heritagepark.ca/" target="_blank" class="bodytext">Heritage Park</a>, 
<a href="http://www.asmac.ab.ca/aerospace/default.asp" target="_blank" class="bodytext">Aero Space Museum</a>, 
<a href="http://www.grainacademymuseum.com/" target="_blank" class="bodytext">Grain Academy Museum</a>, 
<a href="http://themilitarymuseums.ca/" target="_blank" class="bodytext">Military Museums</a> or the 
<a href="http://www.winsportcanada.ca/cop/activities/olympic_hall_of_fame.cfm" target="_blank" class="bodytext">Olympic Hall of Fame and Museum</a>.</li>
</ul>


<p class="maintext">Visit <a href="http://www.visitcalgary.com/ " target="_blank" class="bodytext">Calgary Tourism</a> to find out more.</p>

app/views/pages/application.html.erb
<br><h1>Volunteer Application</h1>
<p class=maintext>We are actively recruiting the following volunteer roles for the D42 2012 Spring Convention:</p>


<table style="width: 73%; border-color: #000000; border-width: 0pt; border-style: solid;" border="0">
<col style="width: 20%" />
<col style="width: 40%" />
<col style="width: 40%" />
<tbody>
<tr>
<td><strong><strong><p class=maintext>Role</strong></strong></td>
<td><strong><strong><p class=maintext>Responsibilities/Sample Activities</strong></strong></td>
<td><strong><p class=maintext>Time Commitment</strong></td>
</tr>
<tr>
<td><strong><p class=maintext>Treasurer</p></strong></td>
<td><p class=maintext>Maintain the budget, track actual expenditures, make deposits and generally report on the financial health of the Convention</p></td>
<td>
<p class=maintext>Bi-weekly meetings with the Convention Co-Chairs</p>
<p class=maintext>Monthly meetings with the Convention planning committee and Co-Chairs</p>
<p class=maintext>Banking activities as required</p>
<p class=maintext>Excel spreadsheet updates as required</p></td>
</tr>
<tr>
<td><strong><p class=maintext>Sponsorship Team Lead</p></strong></td>
<td>
<p class=maintext>Assemble a team of volunteers and lead them</p>
<p class=maintext>Prepare a plan for how you will conduct sponsorship for the Convention then execute to the plan with your team</p>
<p class=maintext>Obtain sponsors to support the Convention through donations of funds, services and/or door prizes to be awarded throughout the weekend</p></td>
<td>
<p class=maintext>Monthly meetings with the Convention planning committee and Co-Chairs</p>
<p class=maintext>Regular meetings with your team</p>
<p class=maintext>Plan creation and management as required</p>
<p class=maintext>Sponsor contact and follow up as required</p>
</td>
</tr>
<tr>
<td><strong><strong><p class=maintext>Sponsorship Team Member</p></strong></strong></td>
<td>
<p class=maintext>Support the Sponsorship Team Lead by working to the team plan</p>
<p class=maintext>Obtain sponsors to support the Convention through donations of funds, services and/or door prizes to be awarded throughout the weekend</p>
</td>
<td>&nbsp;
<p class=maintext>Regular meetings with the Sponsorship Team Lead</p>
<p class=maintext>Sponsor contact and follow up as required</p>
<p class=maintext>Assist Facilities Lead with awarding prizes during the Convention</p>
</td>
</tr>
<tr>
<td>&nbsp;<strong><p class=maintext>Scheduler/ Planner</p></strong></td>
<td>&nbsp;
<p class=maintext>Develop the minute-by-minute schedule then develop work plan of tasks required to make the schedule a reality with the Co-Chairs and Team Leads</p>
Maintain the work plan</td>
<td>&nbsp;
<p class=maintext>Bi-weekly meetings with the Convention Co-Chairs</p>
<p class=maintext>Monthly meetings with the Convention planning committee and Co-Chairs</p>
<p class=maintext>Planning &nbsp;and work plan maintenance activities as required</p>
</td>
</tr>
<tr>
<td>&nbsp;<strong><p class=maintext>Hospitality Suite Team Lead</p></strong></td>
<td>&nbsp;
<p class=maintext>Assemble a team of volunteers and lead them</p>
<p class=maintext>Prepare a plan for how you will operate the Hospitality Suite and associated activities then execute to the plan with your team</p>
</td>
<td>&nbsp;
<p class=maintext>Monthly meetings with the Convention planning committee and Co-Chairs</p>
<p class=maintext>Regular meetings with your team</p>
<p class=maintext>Hospitality Suite preparation and day-of activities as required</p>
</td>
</tr>
<tr>
<td>&nbsp;<strong><p class=maintext>Hospitality Suite Team Members</p></strong></td>
<td>&nbsp;
<p class=maintext>Support the Hospitality Suite Team Lead by working to the team plan</p>
Participate in running the Hospitality Suite Friday and/or Saturday night during the Convention</td>
<td>&nbsp;
<p class=maintext>Regular meetings with the Hospitality Suite Team Lead</p>
<p class=maintext>Activities in the Hospitality Suite during the Convention</p>
</td>
</tr>
</tbody>
</table>


<br>
<h2>Sign Me Up!</h2>
<p class=maintext>Do any of these roles or the thought of joining our fun, dynamic team of Convention volunteers excite you?  If you said YES, send us an email at <a href="mailto:ContactUs@D42TakeTheLead.ca?subject=YES! I want to volunteer!" class=bodytext>ContactUs@D42TakeTheLead.ca</a> to let us know what appeals to you and we’ll be in touch within 2 business days.</p>

app/views/pages/disclaimer.html.erb
<br><h1>Disclaimer</h1> 

<p class="maintext">The D42 Convention Planning Committee (the Committee) maintains this website to provide information to the internet community.  Such information may be subject to amendment and updating without notice.</p>

<p class="maintext">The information contained in this website is for general information purposes only.  Any reliance you place on such information is strictly at your own risk.</p>

<p class="maintext">In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with the use of this website.</p>

<p class="maintext">Through this website you are able to link to other websites which are not under the control of the Committee.  We have no control over the nature, content and availability of those sites.  The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.</p>

<p class="maintext">Every effort is made to keep this website up and running smoothly.  However, the Committee takes no responsibility for and will not be liable for the website being temporarily unavailable due to technical issues beyond our control.</p>

<h2>Data Protection</h2>
 
<p class="maintext">Any personal information submitted via this website, whether by email or other means, will be used solely by the Committee and will not be disclosed to any third parties.  If you wish to view, amend or delete you personal data please <a href="mailto:ContactUs@D42TakeTheLead.ca?subject=Data Protection Inquiry" class=bodytext>contact us</a>.</p>

app/views/pages/educationals.html.erb
<h1>Pages#educationals</h1>
<p>Find me in app/views/pages/educationals.html.erb</p>

app/views/pages/faq.html.erb
<br><h1>Registration FAQ</h1>


<p class=maintext><b>When can I register?</b><br>
You can register at the 2011 D42 Fall Conference in Lethbridge, Alberta or online with your credit card after November 15.  Watch this site for further updates about online registration opening.</p>

<p class=maintext><b>How will I register?</b><br>
This website contains an electronic form where you can safely and securely conduct electronic transactions with your credit card.  Simply complete the form and we’ll charge your credit card with the registration fee.</p>

<p class=maintext><b>How do I let you know my preferences? </b><br>
You can select which education sessions you wish to attend and let us know about your food preferences at the same time you pay for attending the convention.  Simply mark your selections when submitting your registration form.</p>

<p class=maintext><b>How much does the Convention cost and what’s included in the cost?</b><br>
The cost for the convention is $220 until January 31.  From February 1 through March 31, it’s $250. After April 1, the cost increases to $275.  Registration closes April 30 though so don’t delay.
<br><br>
And if you’re a contest official, a contestant, a speaker, a Convention first-timer or  a volunteer,  have we got a deal for you!  You’re eligible for early bird pricing regardless of when you register.  Make sure you register well before April 30 though as we expect to sell out this event.</p>

<p class=maintext><b>What if I only want to attend a subset of the events planned for this weekend?</b><br>
Your Convention package is very economically priced.  It includes 5 meals, snacks, 3 educational sessions, a sensational keynote who will speak at least 3 times throughout the weekend, the infamous hospitality suite and 2 sensational competitions – not to mention the fun-packed networking activities we have planned for you.  </p>

<p class=maintext><b>Can I cancel my registration?</b><br>
Yes.  Send a written cancellation request before March 31, 2012 to the Convention surface mail address and we’ll be more than happy to issue you a refund less a $25 processing fee when the Convention is over.  We regret that because of commitments made for our venue, we will not be able to issue any refunds after March 31.</p>

<p class=maintext><b>Can non-Toastmaster members attend this event?</b><br>
Yes, everyone is welcome.  The pricing model is the same regardless of whether you belong to a Toastmasters club or not.</p>

<p class=maintext><b>What forms of payment are accepted? </b><br>
Our preferred method of payment is credit card (VISA or Mastercard) via the electronic form you’ll find on the Registration page.  We will also accept payment by cheque if it is received at the surface mail address in the Contact Us section prior to March 31, 2012.</p>

<p class=maintext><b>Do I need to pre-register for the education sessions?</b><br>
Yes, please pre-register.  We’d like to let our education session speakers know in advance approximately how many people will attend their session so they can be better prepared for you.  If you decide once you’re at the convention that you’d like to switch education sessions, accommodations will be made.</p>

<p class=maintext><b>Will the information I provide on the electronic registration form be sold to or shared with any 3rd party?</b><br>
No.  We do not sell, rent, or give your personal information to third parties for any reason. </p>

<p class=maintext><b>Who should I contact if I have further questions or need help with registration?</b><br>
Simply send us an email at <a href="mailto:ContactUs@D42TakeTheLead.ca?subject=Contact from the D42 Fall Conference Website" class=bodytext>ContactUs@D42TakeTheLead.ca</a> and someone will reply to your email within 2 business days. </p>

app/views/pages/home.html.erb
<br><h1>Welcome to the District 42 2012 Spring Convention: Take the Lead!</h1>

<p class="maintext">Setting yourself apart from others to assure you are front of mind when opportunities present themselves – whether of a personal or business nature – is never easy.   Making sure that your teams – whether volunteer or paid – are effective in all they do takes work.  Join us May 4-6, 2012 at the District 42 (D42) Spring Convention and we’ll equip you with tools and thought leadership to help you Take the Lead in all you do.</p>

<p class="maintext">Come and experience all that this year’s D42 Spring Convention has to offer – from inspiring keynote presentations and valuable education sessions touching on a variety of critical leadership topics to inspiring competitions sure to leave you wanting more.</p>

<p class="maintext">We expect to SELL OUT, so register early to secure a spot.  Don’t forget to book your accommodation at the Radisson Hotel Calgary Airport at the same time as those spots are limited too.</p>
 
<p class="maintext">See you May 4, 5, 6 2012 in Calgary!</p>

app/views/pages/our_sponsors.html.erb
<br><h1>2012 Sponsors</h1>
<p class="maintext">Our sincere thanks to our sponsors who are helping to make this event the success it is.</p>

<%= image_tag("Rad_calgary_Logo.png") %>

app/views/pages/prizes.html.erb
<h1>Pages#prizes</h1>
<p>Find me in app/views/pages/prizes.html.erb</p>

app/views/pages/registration.html.erb
<br><h1>Registration</h1>
<p class=maintext>Have we got a deal for you!  If you’re planning to attend the D42 2011 Fall Conference in Lethbridge you can register early.  We’ll have forms for you to complete there and you’ll be able to pay in person by debit or credit card.  And the added bonus?  We’ll enter your name into a draw for a chance to win back your registration!  </p>

<p class=maintext>Registration for everyone else opens November 15, 2011 and closes April 30, 2012 or until we sell out, whichever comes first.  We’re using a graduated pay system this time though so the earlier you enter, the lower the cost.</p>

<h2>Price Schedule</h2>
<table style="width: 65%; border-color: #000000; border-width: 0pt; border-style: solid;" border="0">
<col style="width: 20%" />
<col style="width: 22%" />
<col style="width: 10%" />
<col style="width: 48%" />
<tbody>
<tr>
<td>Special Draw<strong><strong><br /></strong></strong></td>
<td><strong><strong></strong></strong>Nov 6</td>
<td><strong></strong>$220 </td>
<td>Limited registration in Lethbridge</td>
</tr>
<tr>
<td><strong></strong>Early Bird</td>
<td>Nov 15 - Jan 31</td>
<td>$220</td>
<td>Early bird pricing for everyone and always for first timers, District Officers, and contestants</td>
</tr>
<tr>
<td>Regular</td>
<td>Feb 1 - Mar 31</td>
<td>$250</td>
<td>First price increase</td>
</tr>
<tr>
<td>Just In Time</td>
<td>Apr 1 - Apr 30</td>
<td>$275</td>
<td>Last price increase</td>
</tr>
<tr>
<td>Missed Out</td>
<td>May 1 - 4</td>
<td>n/a</td>
<td>Sorry &ndash; registration is closed</td>
</tr>
</tbody>
</table>

<h2>Payment Options</h2>
<p class=maintext>When in Lethbridge at the D42 2011 Fall Conference, you can pay by debit or credit card.  After that, we’ll be accepting credit card via the online registration form or paper form with cheque mailed to the surface mail address found on the <%= link_to "Contact Us", contact_us_path, :class => "bodytext" %> page.  Credit cards we accept include VISA and Mastercard.</p>

<h2>Admission to Convention Events</h2>
<p class=maintext>The ID badge you receive at check in your first day of the Convention will give you full admission to all of the weekend’s events.  Be sure to bring it with your everywhere that weekend for admission to the competitions, meals, keynotes, and education sessions.</p>

<h2>Changes to Registration</h2>
<p class=maintext>Should you need to change an education session you selected during registration, don’t  worry.  We’ll be able to accommodate you once you're onsite at the Convention.</p>

<h2>Need Help?</h2>
<p class=maintext>Email us at <a href="mailto:ContactUs@D42TakeTheLead.ca?subject=Contact from the D42 Fall Conference Website" class=bodytext>ContactUs@D42TakeTheLead.ca</a> and we’ll be happy to respond to your email within 2 business days.</p>

app/views/pages/volunteers.html.erb
<br><h1>Volunteers</h1>
<p class=maintext>The theme for this year’s Convention is <i>Take the Lead</i> and there’s no better way to live the Convention theme than to take an active role volunteering to make the event a success!

<p class=maintext>Many hands make light work and never has this been as well demonstrated as by the Toastmasters who are contributing to this Convention.   

<h2>Benefits of Volunteering</h2>
<ul class=mainlist>
<li>Learn firsthand how rewarding it is to work behind-the-scene at a Toastmasters' Convention</li>
<li>Develop your leadership skills by providing your ideas and influence</li>
<li>Meet other fellow Toastmasters you might not have had a chance to meet without this opportunity</li>
<li>Some of our volunteer roles actually let you take credit for your contributions in your Competent Leader (CL) manual</li>
<li>Take advantage of early-bird pricing right up until April 30 when registration closes (although we don't recommend you wait this long as we plan to sell out before then)</li>
</ul>

<h2>Sign Me Up!</h2>
<p class=maintext>Interested in joining our fun, dynamic team of Convention volunteers?  Check out the roles we’re recruiting for on the <%= link_to "Volunteer Application", application_path, :class => "bodytext" %> page then pop us an email at <a href="mailto:ContactUs@D42TakeTheLead.ca?subject=YES! I want to volunteer!" class=bodytext>ContactUs@D42TakeTheLead.ca</a> to let us know what appeals to you.  We’ll be in touch within 2 business days.</p>